package ru.nsu.kondrenko.model;

public enum ContextState {
    IDLE,
    REPAINTING,

    OPENING_FILE,
    SAVING_FILE,
    EXITING,

    CHOOSING_COLOR,
    CHOOSING_THICKNESS,
    CHOOSING_NUMBER_OF_SIDES,
    CHOOSING_RADIUS,
    CHOOSING_ROTATION,

    ERROR,

    DISPLAYING_HELP,
    DISPLAYING_ABOUT
}
