package ru.nsu.kondrenko.model;

public enum ContextState {
    IDLE,
    REPAINTING,
    CLEARING,

    OPENING_FILE,
    SAVING_FILE,
    EXITING,

    CHANGING_COLOR,
    CHANGING_THICKNESS,
    CHANGING_NUMBER_OF_SIDES,
    CHANGING_RADIUS,
    CHANGING_ROTATION,

    DISPLAYING_ERROR,
    DISPLAYING_HELP,
    DISPLAYING_ABOUT
}
